server:
  port: 9401
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-peer1:9101/eureka/,http://eureka-server-peer2:9102/eureka/,http://eureka-server-peer3:9103/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: discovery-service

logging:
  config: classpath:logback.xml