server:
  port: 9131
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9101/eureka/

#spring:
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config-service